---

- name: Logstash Input config
  template:
    src:   etc/logstash/conf.d/input.conf.j2
    dest:  "{{logstash_conf_dir}}/input.conf"
    owner: "root"
    group: "root"
    mode:  "0644"
  notify: logstash restart
  tags:
    - logstash_config
    - logstash_input

- name: Logstash Filter config
  template:
    src:   etc/logstash/conf.d/filters.conf.j2
    dest:  "{{logstash_conf_dir}}/filters.conf"
    owner: "root"
    group: "root"
    mode:  "0644"
  notify: logstash restart
  tags:
    - logstash_config
    - logstash_filter

- name: Logstash Output config
  template:
    src:  etc/logstash/conf.d/output.conf.j2
    dest: "{{logstash_conf_dir}}/output.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: logstash restart
  tags:
    - logstash_config
    - logstash_output

- name: Logstash Daemon opts
  template:
    src:   etc/default/logstash.j2
    dest:  "{{logstash_defaults_cfg}}"
    owner: "root"
    group: "root"
    mode:  "0644"
  notify: logstash restart
  tags:
    - logstash_config

- name: use wazuh default config file
  template:
    src=etc/logstash/conf.d/01-ossec-singlehost.conf
    dest={{logstash_conf_dir}}/01-ossec-singlehost.conf
  when: "{{logstash_config_wazuh_default}}"
  notify: logstash restart

- name: copy custom dynamic template to tmp folder
  template:
    src=logstash.dynamic.template
    dest=/tmp/logstash.dynamic.template
  when: "{{logstash_cloudtrail_template}}"
  tags: cloudtrail-template

- name: import custom dynamic template as default
  shell: curl -XPUT 'http://localhost:9200/_template/logstash' -d@/tmp/logstash.dynamic.template
  tags: cloudtrail-template

# vi:ts=2:sw=2:et:ft=yaml
